### ISSUE TITLE
images

### ISSUE THREAD

**Issue by mbedcode** [mbedcode/mbedcode#1]
![mbedcode](https://user-images.githubusercontent.com/58227435/100896672-1c47f900-347c-11eb-816f-a9fdf2ee9bb2.png)
<img width="1008" alt="Bane" src="https://user-images.githubusercontent.com/58227435/101261465-9aaed000-36f4-11eb-86ec-24148df1f9d8.png">

**Comment by Senshi111** [comment]
![ngAddFontAwesome](https://user-images.githubusercontent.com/40372242/101261468-b5eeff00-3737-11eb-9405-5b53659294ce.png)
